package store

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPostgresV7ArchiveMigrationStructure(t *testing.T) {
	t.Parallel()

	wanted := []string{
		`ALTER TABLE aliases ADD COLUMN credential_ciphertext TEXT NOT NULL DEFAULT ''`,
		`CREATE TABLE archived_messages (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
		`CREATE TABLE alias_messages (
			alias_id BIGINT NOT NULL REFERENCES aliases(id) ON DELETE CASCADE`,
	}
	paths := []struct {
		name       string
		statements []string
	}{
		{name: "fresh v7", statements: postgresSchemaV7},
		{name: "v6 to v7", statements: postgresMigrateV6ToV7},
	}
	for _, path := range paths {
		path := path
		t.Run(path.name, func(t *testing.T) {
			t.Parallel()
			joined := normalizeSQL(strings.Join(path.statements, " "))
			for _, statement := range wanted {
				if !strings.Contains(joined, normalizeSQL(statement)) {
					t.Errorf("%s PostgreSQL migration is missing %q", path.name, normalizeSQL(statement))
				}
			}
			for _, statement := range []string{
				`DROP TABLE consumed_messages`,
				`DROP TABLE imap_seen_tasks`,
				`DROP TABLE pending_alias_api_keys`,
				`DROP TABLE latest_messages`,
				`ALTER TABLE aliases DROP COLUMN api_key_prefix`,
			} {
				if strings.Contains(joined, normalizeSQL(statement)) {
					t.Errorf("%s PostgreSQL migration contains compatibility-breaking statement %q",
						path.name, normalizeSQL(statement))
				}
			}
		})
	}

	fresh := normalizeSQL(strings.Join(postgresSchemaV8, " "))
	convergenceSQL := normalizeSQL(strings.Join(postgresSchemaConvergence, " "))
	credentialConvergenceSQL := normalizeSQL(strings.Join(postgresAliasCredentialModeConvergence, " "))
	for _, statement := range []string{
		`api_key_prefix TEXT NOT NULL`,
		`CREATE TABLE latest_messages`,
		`CREATE TABLE pending_alias_api_keys`,
		`CREATE TABLE consumed_messages`,
		`CREATE TABLE imap_seen_tasks`,
	} {
		if !strings.Contains(fresh, normalizeSQL(statement)) {
			t.Errorf("fresh v7 PostgreSQL schema is missing compatibility structure %q", normalizeSQL(statement))
		}
	}

	const convergenceIndex = `CREATE INDEX IF NOT EXISTS alias_messages_alias_uid_idx
		ON alias_messages(alias_id, mailbox_uid DESC)`
	if !containsNormalizedSQL(postgresSchemaConvergence, convergenceIndex) {
		t.Errorf("PostgreSQL v7 convergence is missing %q", normalizeSQL(convergenceIndex))
	}
	for _, statement := range []string{
		`CREATE TABLE IF NOT EXISTS latest_messages`,
		`CREATE TABLE IF NOT EXISTS pending_alias_api_keys`,
		`CREATE TABLE IF NOT EXISTS consumed_messages`,
		`CREATE TABLE IF NOT EXISTS imap_seen_tasks`,
		`CREATE INDEX IF NOT EXISTS imap_seen_tasks_account_created_idx
			ON imap_seen_tasks(account_id, created_at, uid_validity, uid)`,
		`credential_mode_missing`,
		`IF credential_mode_missing THEN`,
		`ALTER TABLE aliases ADD COLUMN credential_mode`,
		`SET credential_mode = 'v2'`,
		`credential_version > 0`,
		`octet_length(api_key_hash) = 32`,
		`octet_length(imap_password_hash) = 32`,
		`octet_length(refresh_token_hash) = 32`,
	} {
		wanted := normalizeSQL(statement)
		if !strings.Contains(convergenceSQL, wanted) && !strings.Contains(credentialConvergenceSQL, wanted) {
			t.Errorf("PostgreSQL v7 convergence is missing repair statement %q", normalizeSQL(statement))
		}
	}
}

func TestPostgresRestoreSupportsV4ThroughV8AndStrictlyValidatesExtensions(t *testing.T) {
	t.Parallel()

	scriptPath := filepath.Join("..", "..", "docker", "postgres-entrypoint.sh")
	contents, err := os.ReadFile(scriptPath)
	if err != nil {
		t.Fatalf("read PostgreSQL restore entrypoint: %v", err)
	}
	script := string(contents)

	wanted := []string{
		`case "$auto_alias_table_count" in`,
		`die "恢复归档中的自动别名 schema 表不完整"`,
		`case "$seen_table_count" in`,
		`die "恢复归档中的消费与 IMAP Seen schema 表不完整"`,
		`optional_required_tables="alias_creation_schedules pending_alias_api_keys"`,
		`optional_required_tables="$optional_required_tables consumed_messages imap_seen_tasks"`,
		`latest_message_table_count=0`,
		`case "$auto_alias_table_count:$seen_table_count:$latest_message_table_count" in`,
		`1:0:0)`,
		`2:2:1)`,
		`*) die "恢复归档中的 v7 兼容 schema 组合不完整" ;;`,
		`message_required_tables="latest_messages"`,
		`message_required_tables=""`,
		`optional_required_tables="alias_creation_schedules archived_messages alias_messages"`,
		`optional_required_tables="alias_creation_schedules pending_alias_api_keys consumed_messages imap_seen_tasks archived_messages alias_messages"`,
		`optional_required_constraints="alias_creation_schedules:alias_creation_schedules_pkey archived_messages:archived_messages_pkey archived_messages:archived_messages_account_id_uid_validity_upstream_uid_key alias_messages:alias_messages_pkey alias_messages:alias_messages_alias_id_mailbox_uid_key"`,
		`optional_required_constraints="alias_creation_schedules:alias_creation_schedules_pkey pending_alias_api_keys:pending_alias_api_keys_pkey consumed_messages:consumed_messages_pkey imap_seen_tasks:imap_seen_tasks_pkey archived_messages:archived_messages_pkey archived_messages:archived_messages_account_id_uid_validity_upstream_uid_key alias_messages:alias_messages_pkey alias_messages:alias_messages_alias_id_mailbox_uid_key"`,
		`optional_required_foreign_keys="alias_creation_schedules:alias_creation_schedules_account_id_fkey archived_messages:archived_messages_account_id_fkey alias_messages:alias_messages_alias_id_fkey alias_messages:alias_messages_message_id_fkey"`,
		`optional_required_foreign_keys="alias_creation_schedules:alias_creation_schedules_account_id_fkey pending_alias_api_keys:pending_alias_api_keys_alias_id_fkey consumed_messages:consumed_messages_alias_id_fkey imap_seen_tasks:imap_seen_tasks_account_id_fkey archived_messages:archived_messages_account_id_fkey alias_messages:alias_messages_alias_id_fkey alias_messages:alias_messages_message_id_fkey"`,
		`optional_required_indexes="alias_creation_schedules_due_idx aliases_oauth_client_id_idx aliases_imap_password_hash_idx archived_messages_retention_idx alias_messages_alias_uid_idx alias_messages_alias_otp_idx"`,
		`optional_required_indexes="alias_creation_schedules_due_idx imap_seen_tasks_account_created_idx aliases_oauth_client_id_idx aliases_imap_password_hash_idx archived_messages_retention_idx alias_messages_alias_uid_idx alias_messages_alias_otp_idx"`,
		`restored_schema_version NOT IN (4, 5, 6, 7, 8)`,
		`restored_schema_version = 4`,
		`restored_schema_version = 5`,
		`restored_schema_version = 6`,
		`restored_schema_version = 7`,
		`restored_schema_version = 8`,
		`pg_catalog.to_regclass('public.account_mailbox_settings') IS NOT NULL`,
		`mailbox_required_tables="account_mailbox_settings"`,
		`mailbox_required_constraints="account_mailbox_settings:account_mailbox_settings_pkey"`,
		`mailbox_required_foreign_keys="account_mailbox_settings:account_mailbox_settings_account_id_fkey"`,
		`mailbox_required_indexes="account_mailbox_settings_type_idx account_mailbox_settings_custom_suffix_idx"`,
		`$optional_required_tables $mailbox_required_tables; do`,
		`$6 == "public" && $7 == required_table { found_data = 1 }`,
		`die "恢复归档缺少项目必需表或数据段：public.$required_table"`,
		`('v8', 'account_mailbox_settings', 'account_mailbox_settings_custom_suffix_idx')`,
		`RAISE EXCEPTION 'restored schema v8 is missing required compatibility or mailbox tables'`,
		`archive_table_count`,
		`optional_required_sequences="archived_messages_id_seq"`,
		`restored_schema_version BETWEEN 4 AND 6`,
		`restored_schema_version = 7 AND NOT (`,
		`auto_alias_table_count = 1 AND seen_table_count = 0 AND archive_table_count = 2 AND`,
		`auto_alias_table_count = 2 AND seen_table_count = 2 AND archive_table_count = 2 AND`,
		`pg_catalog.to_regclass('public.pending_alias_api_keys') IS NULL`,
		`pg_catalog.to_regclass('public.latest_messages') IS NULL`,
		`pg_catalog.to_regclass('public.consumed_messages') IS NULL`,
		`pg_catalog.to_regclass('public.imap_seen_tasks') IS NULL`,
		`pg_catalog.to_regclass('public.pending_alias_api_keys') IS NOT NULL`,
		`pg_catalog.to_regclass('public.latest_messages') IS NOT NULL`,
		`pg_catalog.to_regclass('public.consumed_messages') IS NOT NULL`,
		`pg_catalog.to_regclass('public.imap_seen_tasks') IS NOT NULL`,
		`RAISE EXCEPTION 'restored schema v7 has an unrecognized compatibility-table set'`,
		`restored_schema_version IN (7, 8) AND
			 pg_catalog.to_regclass('public.latest_messages') IS NOT NULL`,
		`('message', 'latest_messages', 'latest_messages_pkey', ARRAY['alias_id']::TEXT[])`,
		`('message', 'latest_messages', 'latest_messages_alias_id_fkey', 'aliases', ARRAY['alias_id']::TEXT[], ARRAY['id']::TEXT[])`,
		`('auto', 'pending_alias_api_keys', 'pending_alias_api_keys_pkey', ARRAY['alias_id']::TEXT[])`,
		`('seen', 'consumed_messages', 'consumed_messages_pkey', ARRAY['alias_id', 'uid_validity', 'uid']::TEXT[])`,
		`('seen', 'imap_seen_tasks', 'imap_seen_tasks_pkey', ARRAY['account_id', 'uid_validity', 'uid']::TEXT[])`,
		`('auto', 'pending_alias_api_keys', 'pending_alias_api_keys_alias_id_fkey', 'aliases', ARRAY['alias_id']::TEXT[], ARRAY['id']::TEXT[])`,
		`('seen', 'consumed_messages', 'consumed_messages_alias_id_fkey', 'aliases', ARRAY['alias_id']::TEXT[], ARRAY['id']::TEXT[])`,
		`('seen', 'imap_seen_tasks', 'imap_seen_tasks_account_id_fkey', 'accounts', ARRAY['account_id']::TEXT[], ARRAY['id']::TEXT[])`,
		`('seen', 'imap_seen_tasks', 'imap_seen_tasks_account_created_idx', ARRAY['account_id', 'created_at', 'uid_validity', 'uid']::TEXT[])`,
		`('mailbox', 'account_mailbox_settings', 'account_mailbox_settings_pkey', ARRAY['account_id']::TEXT[])`,
		`('mailbox', 'account_mailbox_settings', 'account_mailbox_settings_account_id_fkey', 'accounts', ARRAY['account_id']::TEXT[], ARRAY['id']::TEXT[])`,
		`('mailbox', 'account_mailbox_settings', 'account_mailbox_settings_type_idx', ARRAY['mailbox_type', 'account_id']::TEXT[])`,
		`required.extension_group <> 'mailbox' OR restored_schema_version = 8`,
		`ARRAY['account_id']::TEXT[]`,
		`ARRAY['alias_id']::TEXT[]`,
		`ARRAY['alias_id', 'uid_validity', 'uid']::TEXT[]`,
		`ARRAY['account_id', 'uid_validity', 'uid']::TEXT[]`,
		`constraint_state.confrelid = pg_catalog.to_regclass('public.' || required.referenced_table)`,
		`constraint_state.confdeltype = 'c'`,
		`access_method.amname = 'btree'`,
		`NOT index_metadata.indisunique`,
		`index_metadata.indpred IS NULL`,
		`index_metadata.indexprs IS NULL`,
		`ARRAY['enabled', 'next_run_at', 'account_id']::TEXT[]`,
		`ARRAY['account_id', 'created_at', 'uid_validity', 'uid']::TEXT[]`,
		`index_state.relname = 'account_mailbox_settings_custom_suffix_idx'`,
		`AND index_metadata.indisunique`,
		`AND index_metadata.indnkeyatts = 1`,
		`AND index_metadata.indnatts = 1`,
		`AND index_metadata.indpred IS NOT NULL`,
		`AND index_metadata.indexprs IS NOT NULL`,
		`) = ARRAY[0]::SMALLINT[]`,
		`) = 'loweremail_suffix'`,
		`) = 'mailbox_type=''custom''::text'`,
		`RAISE EXCEPTION 'restored schema has invalid index account_mailbox_settings.account_mailbox_settings_custom_suffix_idx'`,
	}
	for _, fragment := range wanted {
		if !strings.Contains(script, fragment) {
			t.Errorf("PostgreSQL restore contract is missing %q", fragment)
		}
	}
	if strings.Contains(script, "data_migrations alias_creation_schedules") ||
		strings.Contains(script, "data_migrations consumed_messages") {
		t.Fatal("PostgreSQL restore preflight still requires extension tables for every archive")
	}
	for _, obsolete := range []string{
		`[ "$auto_alias_table_count" -eq 1 ] || die "恢复归档中的 v7 自动别名 schema 不完整"`,
		`[ "$auto_alias_table_count" -eq 2 ] || die "恢复归档中的 v7 自动别名 schema 不完整"`,
		`[ "$seen_table_count" -eq 0 ] || die "恢复归档中的 v7 schema 仍包含已删除的 Seen 表"`,
		`[ "$seen_table_count" -eq 2 ] || die "恢复归档中的 v7 消费与 IMAP Seen schema 不完整"`,
		`auto_alias_table_count <> 1 OR seen_table_count <> 0 OR archive_table_count <> 2 OR`,
		`auto_alias_table_count <> 2 OR seen_table_count <> 2 OR archive_table_count <> 2 OR`,
	} {
		if strings.Contains(script, obsolete) {
			t.Errorf("PostgreSQL restore contract still contains obsolete v7 compatibility rule %q", obsolete)
		}
	}
}

func TestPostgresMigrationExecutesV0V3V4V5V6V7V8Paths(t *testing.T) {
	t.Parallel()

	freshAdmin := postgresSchemaV8[0]
	syncState := postgresMigrateV3ToV4[len(postgresMigrateV3ToV4)-2]
	autoSchedule := postgresMigrateV4ToV5[0]
	consumedMessages := postgresMigrateV5ToV6[0]
	compatValidation := postgresV5CompatibilityMigration[0]
	compatAutoSchedule := postgresV5CompatibilityMigration[1]
	compatConsumedMessages := postgresV5CompatibilityMigration[3]
	archiveTable := postgresMigrateV6ToV7[10]
	mailboxSettingsTable := postgresMigrateV7ToV8[0]
	archiveIndexConvergence := `CREATE INDEX IF NOT EXISTS archived_messages_retention_idx
		ON archived_messages(content_state, internal_date, id)`

	paths := []struct {
		version           int
		wanted            []string
		unwanted          []string
		wantVersionUpdate bool
	}{
		{0, []string{freshAdmin, syncState, autoSchedule, consumedMessages, archiveTable, mailboxSettingsTable}, nil, true},
		{3, []string{syncState, autoSchedule, consumedMessages, archiveTable, mailboxSettingsTable}, []string{freshAdmin}, true},
		{4, []string{autoSchedule, consumedMessages, archiveTable, mailboxSettingsTable}, []string{freshAdmin, syncState}, true},
		{5, []string{compatValidation, compatAutoSchedule, compatConsumedMessages, archiveTable, mailboxSettingsTable}, []string{freshAdmin, syncState, autoSchedule, consumedMessages}, true},
		// Compatibility-table repair statements are part of v7 convergence and
		// therefore may execute even when the source is already v6 or v7.
		{6, []string{archiveTable, mailboxSettingsTable}, []string{freshAdmin, syncState, autoSchedule, consumedMessages, compatValidation, compatAutoSchedule}, true},
		{7, []string{mailboxSettingsTable}, []string{freshAdmin, syncState, autoSchedule, consumedMessages, compatValidation, compatAutoSchedule, archiveTable}, true},
		{8, nil, []string{freshAdmin, syncState, autoSchedule, consumedMessages, compatValidation, compatAutoSchedule, archiveTable}, false},
	}
	for _, path := range paths {
		path := path
		t.Run(fmt.Sprintf("v%d", path.version), func(t *testing.T) {
			capture := &postgresMigrationCaptureDriver{version: path.version}
			driverName := fmt.Sprintf("icloud-api-postgres-v8-path-%p", capture)
			sql.Register(driverName, capture)
			raw, err := sql.Open(driverName, "")
			if err != nil {
				t.Fatalf("open PostgreSQL migration capture: %v", err)
			}
			raw.SetMaxOpenConns(1)
			t.Cleanup(func() { _ = raw.Close() })

			db := newStore(raw, dialectPostgres)
			if err := db.migratePostgres(context.Background()); err != nil {
				t.Fatalf("migrate PostgreSQL schema v%d: %v", path.version, err)
			}
			for _, statement := range path.wanted {
				if !containsNormalizedSQL(capture.statements, statement) {
					t.Errorf("PostgreSQL v%d path did not execute %q", path.version, normalizeSQL(statement))
				}
			}
			for _, statement := range path.unwanted {
				if containsNormalizedSQL(capture.statements, statement) {
					t.Errorf("PostgreSQL v%d path unexpectedly executed %q", path.version, normalizeSQL(statement))
				}
			}
			if !containsNormalizedSQL(capture.statements, archiveIndexConvergence) {
				t.Errorf("PostgreSQL v%d path did not converge the archive retention index", path.version)
			}

			updatedVersion := false
			for _, statement := range capture.statements {
				if strings.HasPrefix(normalizeSQL(statement), "update schema_migrations set version =") {
					updatedVersion = true
					break
				}
			}
			if updatedVersion != path.wantVersionUpdate {
				t.Errorf("PostgreSQL v%d version update = %t, want %t", path.version, updatedVersion, path.wantVersionUpdate)
			}
			if path.version == 3 &&
				(postgresMigrationStatementIndex(capture.statements, syncState) >=
					postgresMigrationStatementIndex(capture.statements, autoSchedule) ||
					postgresMigrationStatementIndex(capture.statements, autoSchedule) >=
						postgresMigrationStatementIndex(capture.statements, consumedMessages) ||
					postgresMigrationStatementIndex(capture.statements, consumedMessages) >=
						postgresMigrationStatementIndex(capture.statements, archiveTable)) {
				t.Error("PostgreSQL v3 path did not apply v3-to-v4, v4-to-v5, v5-to-v6, and v6-to-v7 in order")
			}
		})
	}
}

type postgresMigrationCaptureDriver struct {
	version    int
	statements []string
}

func (d *postgresMigrationCaptureDriver) Open(string) (driver.Conn, error) {
	return &postgresMigrationCaptureConn{capture: d}, nil
}

type postgresMigrationCaptureConn struct {
	capture *postgresMigrationCaptureDriver
}

func (c *postgresMigrationCaptureConn) Prepare(string) (driver.Stmt, error) {
	return nil, fmt.Errorf("prepare is not implemented")
}

func (c *postgresMigrationCaptureConn) Close() error { return nil }

func (c *postgresMigrationCaptureConn) Begin() (driver.Tx, error) {
	return &postgresMigrationCaptureTx{}, nil
}

func (c *postgresMigrationCaptureConn) BeginTx(context.Context, driver.TxOptions) (driver.Tx, error) {
	return &postgresMigrationCaptureTx{}, nil
}

func (c *postgresMigrationCaptureConn) ExecContext(
	_ context.Context,
	query string,
	_ []driver.NamedValue,
) (driver.Result, error) {
	c.capture.statements = append(c.capture.statements, query)
	return driver.RowsAffected(1), nil
}

func (c *postgresMigrationCaptureConn) QueryContext(
	_ context.Context,
	query string,
	_ []driver.NamedValue,
) (driver.Rows, error) {
	if !strings.Contains(normalizeSQL(query), "select version from schema_migrations") {
		return nil, fmt.Errorf("unexpected PostgreSQL migration query: %s", query)
	}
	return &postgresMigrationVersionRows{version: int64(c.capture.version)}, nil
}

type postgresMigrationCaptureTx struct{}

func (*postgresMigrationCaptureTx) Commit() error   { return nil }
func (*postgresMigrationCaptureTx) Rollback() error { return nil }

type postgresMigrationVersionRows struct {
	version int64
	read    bool
}

func (*postgresMigrationVersionRows) Columns() []string { return []string{"version"} }
func (*postgresMigrationVersionRows) Close() error      { return nil }

func (r *postgresMigrationVersionRows) Next(values []driver.Value) error {
	if r.read {
		return io.EOF
	}
	r.read = true
	values[0] = r.version
	return nil
}

func postgresMigrationStatementIndex(statements []string, wanted string) int {
	wanted = normalizeSQL(wanted)
	for index, statement := range statements {
		if normalizeSQL(statement) == wanted {
			return index
		}
	}
	return -1
}
