package domain

import "time"

const (
	SyncStatusPending = "pending"
	SyncStatusOK      = "ok"
	SyncStatusError   = "error"

	AppleAliasConfirmationPending = "APPLE_ALIAS_CONFIRMATION_PENDING"

	MaxEnabledAliasesPerAccount = 1000
)

type Admin struct {
	ID              int64
	Username        string
	PasswordHash    string
	PasswordVersion int64
	CreatedAt       time.Time
}

type Session struct {
	AdminID         int64
	Username        string
	PasswordVersion int64
	CSRF            string
	ExpiresAt       time.Time
}

type Account struct {
	ID                 int64
	Name               string
	Email              string
	IMAPHost           string
	IMAPPort           int
	IMAPUsername       string
	PasswordCiphertext string
	Enabled            bool
	LastSyncStatus     string
	LastSyncError      string
	LastSyncedAt       *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AliasCount         int
}

// AppleWebSession stores the encrypted Apple web session associated with an
// account. Ciphertext is opaque to the persistence layer.
type AppleWebSession struct {
	AccountID       int64
	Ciphertext      string
	AppleID         string
	Region          string
	Authenticated   bool
	LastValidatedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

// AliasCreationSchedule is the persisted per-account plan used by the
// Hide My Email auto-creation worker. PlannedAt contains only future attempts
// and is stored as absolute UTC times so process restarts do not reshuffle a
// live cycle.
type AliasCreationSchedule struct {
	AccountID        int64
	Enabled          bool
	PlannedAt        []time.Time
	NextRunAt        *time.Time
	LastAttemptedAt  *time.Time
	LastCreatedAt    *time.Time
	LastAliasAddress string
	LastError        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// PendingAliasAPIKey is an automatically created alias whose one-time raw API
// key is still waiting for an administrator to retrieve and acknowledge.
// APIKeyCiphertext is never exposed outside trusted persistence/service code.
type PendingAliasAPIKey struct {
	Alias            Alias
	APIKeyCiphertext string
	CreatedAt        time.Time
}

type Alias struct {
	ID               int64
	AccountID        int64
	AccountEmail     string
	Address          string
	Label            string
	APIKeyHash       []byte
	APIKeyPrefix     string
	Enabled          bool
	LastSyncStatus   string
	LastSyncError    string
	LastSyncedAt     *time.Time
	LastAccessedAt   *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LatestReceivedAt *time.Time
}

// AliasImportCandidate is a remotely discovered alias with an API key that
// has already been generated by the caller.
type AliasImportCandidate struct {
	Address      string
	Label        string
	APIKeyHash   []byte
	APIKeyPrefix string
	Active       bool
}

type AliasImportConflict struct {
	Address              string
	ExistingAliasID      int64
	ExistingAccountID    int64
	ExistingAccountEmail string
}

type AliasImportResult struct {
	Created               []Alias
	Existing              []Alias
	Conflicts             []AliasImportConflict
	ImportedDisabledCount int
}

type MailAddress struct {
	Name  string `json:"name,omitempty"`
	Email string `json:"email"`
}

type Attachment struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
}

type SnapshotState string

const (
	SnapshotFound   SnapshotState = "found"
	SnapshotEmpty   SnapshotState = "empty"
	SnapshotUnknown SnapshotState = "unknown"
)

type LatestMessage struct {
	AliasID       int64
	UIDValidity   uint32
	UID           uint32
	MessageID     string
	InternalDate  time.Time
	HeaderDate    *time.Time
	From          []MailAddress
	To            []MailAddress
	CC            []MailAddress
	Subject       string
	TextBody      string
	HTMLBody      string
	Attachments   []Attachment
	BodyTruncated bool
	SyncedAt      time.Time
	SnapshotState SnapshotState `json:"-"`
}

// IMAPSyncState is the account-level cursor for one selected mailbox
// generation. LastUID is the examined high-water mark. A reset establishes a
// bounded recent baseline; normal incremental runs may skip UIDs already marked
// Seen by this service, but never advance past an unread UID omitted from the
// committed batch. UpdatedAt is when this mailbox position was observed, not
// when it committed.
type IMAPSyncState struct {
	AccountID   int64
	UIDValidity uint32
	LastUID     uint32
	UpdatedAt   time.Time
}

// SeenTask is a durable request to mark one message as seen in its
// account's selected mailbox. UIDVALIDITY scopes UID to one mailbox
// generation, so workers must compare it with the currently selected mailbox
// before applying the task.
type SeenTask struct {
	AccountID   int64
	UIDValidity uint32
	UID         uint32
	CreatedAt   time.Time
}

// MailboxSnapshotPosition identifies the locally published latest message for
// one alias. Sync uses these positions to validate all current snapshots with
// one shared IMAP command before reconciling expunged messages.
type MailboxSnapshotPosition struct {
	AliasID     int64
	UIDValidity uint32
	UID         uint32
}

// MailboxSyncResult contains only changed alias snapshots during an
// incremental run. Reset establishes a bounded baseline for an initial,
// invalidated-cursor, or new-generation scan. A bounded reset only includes
// aliases it found. SnapshotEmpty means the local snapshot was authoritatively
// invalidated and no replacement was found in the bounded reconciliation window.
type MailboxSyncResult struct {
	Messages map[int64]LatestMessage
	State    IMAPSyncState
	Reset    bool
	// HasMore means later unread UIDs remain beyond State.LastUID.
	HasMore bool
	// TargetUID is the selected mailbox upper bound observed for this batch.
	// It is transient progress metadata and is not persisted with the cursor.
	TargetUID uint32
}

type MailboxBinding struct {
	Alias   Alias
	Account Account
	Message *LatestMessage
}

type AuditLog struct {
	ID           int64
	AdminID      *int64
	Username     string
	Action       string
	ResourceType string
	ResourceID   string
	Result       string
	IP           string
	RequestID    string
	Detail       string
	CreatedAt    time.Time
}
