package domain

import "time"

const (
	SyncStatusPending = "pending"
	SyncStatusOK      = "ok"
	SyncStatusError   = "error"

	MaxEnabledAliasesPerAccount = 1000
)

type Admin struct {
	ID              int64
	Username        string
	PasswordHash    string
	PasswordVersion int64
	CreatedAt       time.Time
}

type Session struct {
	AdminID         int64
	Username        string
	PasswordVersion int64
	CSRF            string
	ExpiresAt       time.Time
}

type Account struct {
	ID                 int64
	Name               string
	Email              string
	IMAPHost           string
	IMAPPort           int
	IMAPUsername       string
	PasswordCiphertext string
	Enabled            bool
	LastSyncStatus     string
	LastSyncError      string
	LastSyncedAt       *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AliasCount         int
}

// AppleWebSession stores the encrypted Apple web session associated with an
// account. Ciphertext is opaque to the persistence layer.
type AppleWebSession struct {
	AccountID       int64
	Ciphertext      string
	AppleID         string
	Region          string
	Authenticated   bool
	LastValidatedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Alias struct {
	ID               int64
	AccountID        int64
	AccountEmail     string
	Address          string
	Label            string
	APIKeyHash       []byte
	APIKeyPrefix     string
	Enabled          bool
	LastSyncStatus   string
	LastSyncError    string
	LastSyncedAt     *time.Time
	LastAccessedAt   *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LatestReceivedAt *time.Time
}

// AliasImportCandidate is a remotely discovered alias with an API key that
// has already been generated by the caller.
type AliasImportCandidate struct {
	Address      string
	Label        string
	APIKeyHash   []byte
	APIKeyPrefix string
	Active       bool
}

type AliasImportConflict struct {
	Address              string
	ExistingAliasID      int64
	ExistingAccountID    int64
	ExistingAccountEmail string
}

type AliasImportResult struct {
	Created               []Alias
	Existing              []Alias
	Conflicts             []AliasImportConflict
	ImportedDisabledCount int
}

type MailAddress struct {
	Name  string `json:"name,omitempty"`
	Email string `json:"email"`
}

type Attachment struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size"`
}

type SnapshotState string

const (
	SnapshotFound   SnapshotState = "found"
	SnapshotEmpty   SnapshotState = "empty"
	SnapshotUnknown SnapshotState = "unknown"
)

type LatestMessage struct {
	AliasID       int64
	UIDValidity   uint32
	UID           uint32
	MessageID     string
	InternalDate  time.Time
	HeaderDate    *time.Time
	From          []MailAddress
	To            []MailAddress
	CC            []MailAddress
	Subject       string
	TextBody      string
	HTMLBody      string
	Attachments   []Attachment
	BodyTruncated bool
	SyncedAt      time.Time
	SnapshotState SnapshotState `json:"-"`
}

// IMAPSyncState is the account-level cursor for one selected mailbox
// generation. LastUID is the consumed high-water mark. A reset establishes a
// bounded recent baseline; normal incremental runs never advance it past an
// existing UID that was not processed. UpdatedAt is when this mailbox position
// was observed, not when it committed.
type IMAPSyncState struct {
	AccountID   int64
	UIDValidity uint32
	LastUID     uint32
	UpdatedAt   time.Time
}

// MailboxSnapshotPosition identifies the locally published latest message for
// one alias. Sync uses these positions to validate all current snapshots with
// one shared IMAP command before reconciling expunged messages.
type MailboxSnapshotPosition struct {
	AliasID     int64
	UIDValidity uint32
	UID         uint32
}

// MailboxSyncResult contains only changed alias snapshots during an
// incremental run. Reset establishes a bounded baseline for an initial,
// invalidated-cursor, or new-generation scan. A bounded reset only includes
// aliases it found. SnapshotEmpty means the local snapshot was authoritatively
// invalidated and no replacement was found in the bounded reconciliation window.
type MailboxSyncResult struct {
	Messages map[int64]LatestMessage
	State    IMAPSyncState
	Reset    bool
	// HasMore means later actual UIDs remain beyond State.LastUID.
	HasMore bool
}

type MailboxBinding struct {
	Alias   Alias
	Account Account
	Message *LatestMessage
}

type AuditLog struct {
	ID           int64
	AdminID      *int64
	Username     string
	Action       string
	ResourceType string
	ResourceID   string
	Result       string
	IP           string
	RequestID    string
	Detail       string
	CreatedAt    time.Time
}
